### PR TITLE
Updated format of blacklist json to link URL to NFT

### PR DESCRIPTION
**Pull request by bnchk**
Hi, have updated the json format to include linkage of the URL in the scam NFTs to the NFT data it originated from.

When there are 1000's of them will allow clearer analysis in future if
 - projects attack each other trying to load their URLs into blacklist data
 - clearer future analysis of how everything evolves
 - because when there are 1000s no one will be going back to put the linkage in place
 - one place to load information = keeps the data aligned

Hope its of use.  But NB had to google json formats because only used RDBs before, hope its of use and correct structure :-)

### CODE REVIEW

**Comment by adamcazes** [comment]
hey bnchk thanks a lot for your effort here
we will look into the changes, there are some edge cases where this might break stuff on our end but this list does make sense when interacted with outside of a wallet

**Comment by bnchk** [comment]
Updated original pull file with 
 - added 4 new scams found in $scamexamples wallet (all were flagged on pool.pm)
 - correction for your original numbering increments for repeated scams on same project
 - corrected alphabetical order for one record

**Comment by bnchk** [comment]
> hey bnchk thanks a lot for your effort here we will look into the changes, there are some edge cases where this might break stuff on our end but this list does make sense when interacted with outside of a wallet

Nw, hopefully the URL blacklist can be represented by unique list extraction from this format (or similar)

**Comment by adamcazes** [comment]
@bnchk we added 2 new files with the changed structure to include the policies, domains, and stake addresses, with slight modifications to be efficient with our code so thanks again for your suggestion and the new tokens.

this is the new structure for both blacklist & whitelist:
https://github.com/adabox-aio/cardano-shield/commit/61b09d259d93c36afebdc1bc3163dd018120ab37

**Pull request closed without merging**
